[package]
name = "queso"
version = "0.1.0"
authors = ["Mateusz Sowiński-Smętny <matisowagm@gmail.com>"]
edition = "2018"


[dependencies]
phf = { version = "0.8", features = ["macros"] }
clap = "2.33.0"
